version: '3'
services:
# create mariadb  container
  mariadb:
    build: ./requirements/mariadb
    image: mariadb
    container_name: mariadb
    restart: always
    ports:
      - "3306:3306"
    env_file:
      - .env
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - inception

# create nginx container
  nginx:
    build: ./requirements/nginx
    image: nginx
    container_name: nginx
    restart: always
    ports:
      - "443:443"
    volumes:
      - wordpress:/var/www/html/wordpress
    depends_on:
      - wordpress
    networks:
      - inception

# create wordpress container
  wordpress:
    build: ./requirements/wordpress
    image: wordpress
    container_name: wordpress
    ports:
      - "9000:9000"
    restart: always
    env_file:
      - .env
    volumes:
      - wordpress:/var/www/html/wordpress
    depends_on:
      - mariadb
    networks:
      - inception

  # ADDED FOR BONUS --------------------------------------------------

  # create redis container
  redis:
    build: ./requirements/bonus/redis
    image: redis
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    depends_on:
      - wordpress
    volumes:
      - wordpress:/var/www/html/wordpress
    networks:
      - inception
# END OF BONUS --------------------------------------------------

# create a volume for mariadb and wordpress data
volumes:
  mariadb:
    driver: local
    driver_opts:
      type: none
      device: /tmp/data/mariadb
      o: bind
  wordpress:
    driver: local
    driver_opts:
      type: none
      device: /tmp/data/wordpress
      o: bind
# create a network for containers
networks:
  inception:
    driver: bridge